package com.sk.ppk.dao;

import com.sk.ppk.model.Templateinformation;
import java.util.List;
import java.util.Map;

public interface TemplateinformationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table templateinformation
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table templateinformation
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	int insert(Templateinformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table templateinformation
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	int insertSelective(Templateinformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table templateinformation
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	Templateinformation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table templateinformation
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	int updateByPrimaryKeySelective(Templateinformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table templateinformation
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	int updateByPrimaryKey(Templateinformation record);
	
	public List<Templateinformation> getTemplate(Map pagemap);
	public List<Templateinformation> getTemplatebytype(Map pagemap);
	
	public int getTemplateCount(Map pagemap);
	
	int updateStatus(Templateinformation record);
	
	int deldata(Templateinformation record);
}