package com.sk.ppk.model;

import java.util.Date;

public class Dynamicinformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.id
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.id
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private Integer status;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.dynamicname
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private String dynamicname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.dynamictype
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private String dynamictype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.dynamicimage
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private String dynamicimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.dynamicdescribe
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private String dynamicdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.CreatUser
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private String creatuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicinformation.CreatTime
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    private Date creattime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.id
     *
     * @return the value of dynamicinformation.id
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.id
     *
     * @param id the value for dynamicinformation.id
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public Integer getStatus() {
        return status;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.dynamicname
     *
     * @return the value of dynamicinformation.dynamicname
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public String getDynamicname() {
        return dynamicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.dynamicname
     *
     * @param dynamicname the value for dynamicinformation.dynamicname
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setDynamicname(String dynamicname) {
        this.dynamicname = dynamicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.dynamictype
     *
     * @return the value of dynamicinformation.dynamictype
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public String getDynamictype() {
        return dynamictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.dynamictype
     *
     * @param dynamictype the value for dynamicinformation.dynamictype
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setDynamictype(String dynamictype) {
        this.dynamictype = dynamictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.dynamicimage
     *
     * @return the value of dynamicinformation.dynamicimage
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public String getDynamicimage() {
        return dynamicimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.dynamicimage
     *
     * @param dynamicimage the value for dynamicinformation.dynamicimage
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setDynamicimage(String dynamicimage) {
        this.dynamicimage = dynamicimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.dynamicdescribe
     *
     * @return the value of dynamicinformation.dynamicdescribe
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public String getDynamicdescribe() {
        return dynamicdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.dynamicdescribe
     *
     * @param dynamicdescribe the value for dynamicinformation.dynamicdescribe
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setDynamicdescribe(String dynamicdescribe) {
        this.dynamicdescribe = dynamicdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.CreatUser
     *
     * @return the value of dynamicinformation.CreatUser
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public String getCreatuser() {
        return creatuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.CreatUser
     *
     * @param creatuser the value for dynamicinformation.CreatUser
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setCreatuser(String creatuser) {
        this.creatuser = creatuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicinformation.CreatTime
     *
     * @return the value of dynamicinformation.CreatTime
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicinformation.CreatTime
     *
     * @param creattime the value for dynamicinformation.CreatTime
     *
     * @mbggenerated Thu Jun 09 21:08:22 CST 2016
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }
}