package com.sk.ppk.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ID
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.LogName
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String logname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Email
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Type
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.LastLoginTime
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Password
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.RegistrationTime
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private Date registrationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.LastLoginIp
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String lastloginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Contacts
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Telphone
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Company
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.Level
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ID
     *
     * @return the value of member.ID
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ID
     *
     * @param id the value for member.ID
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.LogName
     *
     * @return the value of member.LogName
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getLogname() {
        return logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.LogName
     *
     * @param logname the value for member.LogName
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setLogname(String logname) {
        this.logname = logname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Email
     *
     * @return the value of member.Email
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Email
     *
     * @param email the value for member.Email
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Type
     *
     * @return the value of member.Type
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Type
     *
     * @param type the value for member.Type
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.LastLoginTime
     *
     * @return the value of member.LastLoginTime
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.LastLoginTime
     *
     * @param lastlogintime the value for member.LastLoginTime
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Password
     *
     * @return the value of member.Password
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Password
     *
     * @param password the value for member.Password
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.RegistrationTime
     *
     * @return the value of member.RegistrationTime
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public Date getRegistrationtime() {
        return registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.RegistrationTime
     *
     * @param registrationtime the value for member.RegistrationTime
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setRegistrationtime(Date registrationtime) {
        this.registrationtime = registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.LastLoginIp
     *
     * @return the value of member.LastLoginIp
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.LastLoginIp
     *
     * @param lastloginip the value for member.LastLoginIp
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Contacts
     *
     * @return the value of member.Contacts
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Contacts
     *
     * @param contacts the value for member.Contacts
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Telphone
     *
     * @return the value of member.Telphone
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Telphone
     *
     * @param telphone the value for member.Telphone
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Company
     *
     * @return the value of member.Company
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Company
     *
     * @param company the value for member.Company
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.Level
     *
     * @return the value of member.Level
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.Level
     *
     * @param level the value for member.Level
     *
     * @mbggenerated Wed Jun 15 14:23:45 CST 2016
     */
    public void setLevel(String level) {
        this.level = level;
    }
}