package com.sk.ppk.model;

import java.util.Date;

public class Styleinformation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.ID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.UserID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.WebID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private Integer webid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.StyleName
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private String stylename;
	
    private String styleimg;
	
	private Integer stylemode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.ApplyControl
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private String applycontrol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.Status
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private String statusmode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.CssStyle
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private String cssstyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.CreatUser
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private String creatuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column styleinformation.CreatTime
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	private Date creattime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.ID
	 * @return  the value of styleinformation.ID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public Integer getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.ID
	 * @param id  the value for styleinformation.ID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setId(Integer id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.UserID
	 * @return  the value of styleinformation.UserID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public Integer getUserid()
	{
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.UserID
	 * @param userid  the value for styleinformation.UserID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setUserid(Integer userid)
	{
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.WebID
	 * @return  the value of styleinformation.WebID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public Integer getWebid()
	{
		return webid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.WebID
	 * @param webid  the value for styleinformation.WebID
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setWebid(Integer webid)
	{
		this.webid = webid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.StyleName
	 * @return  the value of styleinformation.StyleName
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public String getStylename()
	{
		return stylename;
	}
	

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.StyleName
	 * @param stylename  the value for styleinformation.StyleName
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setStylename(String stylename)
	{
		this.stylename = stylename;
	}

	public String getStyleimg()
	{
		return styleimg;
	}
	
	public void setStyleimg(String styleimg)
	{
		this.styleimg = styleimg;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.ApplyControl
	 * @return  the value of styleinformation.ApplyControl
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public String getApplycontrol()
	{
		return applycontrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.ApplyControl
	 * @param applycontrol  the value for styleinformation.ApplyControl
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setApplycontrol(String applycontrol)
	{
		this.applycontrol = applycontrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.Status
	 * @return  the value of styleinformation.Status
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public String getStatusmode()
	{
		return statusmode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.Status
	 * @param status  the value for styleinformation.Status
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setStatus(String status)
	{
		this.statusmode = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.CssStyle
	 * @return  the value of styleinformation.CssStyle
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public String getCssstyle()
	{
		return cssstyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.CssStyle
	 * @param cssstyle  the value for styleinformation.CssStyle
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setCssstyle(String cssstyle)
	{
		this.cssstyle = cssstyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.CreatUser
	 * @return  the value of styleinformation.CreatUser
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public String getCreatuser()
	{
		return creatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.CreatUser
	 * @param creatuser  the value for styleinformation.CreatUser
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setCreatuser(String creatuser)
	{
		this.creatuser = creatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column styleinformation.CreatTime
	 * @return  the value of styleinformation.CreatTime
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public Date getCreattime()
	{
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column styleinformation.CreatTime
	 * @param creattime  the value for styleinformation.CreatTime
	 * @mbggenerated  Thu May 05 17:05:26 CST 2016
	 */
	public void setCreattime(Date creattime)
	{
		this.creattime = creattime;
	}
	
	public void setStylemode(int stylemode)
	{
		this.stylemode = stylemode;
	}
	
	public Integer getStylemode()
	{
		return stylemode;
	}

}