package com.sk.ppk.model;

import java.util.Date;

public class Templateinformation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.ID
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private Integer id;
	
	private Integer numberid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.WebsiteType
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private String websitetype;
	
	private Integer status;
	
	private String useful;
	
	private String imagepath;
	
	private String filepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.TemplateType
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private String templatetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.HotDegree
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private String hotdegree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.Color
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private String color;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.Name
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.CreatUser
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private String creatuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column templateinformation.CreatTime
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	private Date creattime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.ID
	 * @return  the value of templateinformation.ID
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public Integer getId()
	{
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.ID
	 * @param id  the value for templateinformation.ID
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setId(Integer id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.ID
	 * @return  the value of templateinformation.ID
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public Integer getNumberId()
	{
		return numberid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.ID
	 * @param id  the value for templateinformation.ID
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setNumberId(Integer numberid)
	{
		this.numberid = numberid;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.WebsiteType
	 * @return  the value of templateinformation.WebsiteType
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public String getWebsitetype()
	{
		return websitetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.WebsiteType
	 * @param websitetype  the value for templateinformation.WebsiteType
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setWebsitetype(String websitetype)
	{
		this.websitetype = websitetype;
	}

	public Integer getStatus()
	{
		return status;
	}
	
	public void setStatus(Integer status)
	{
		this.status = status;
	}
	
	public String getUseFul()
	{
		return useful;
	}
	
	public void setUseFul(String useful)
	{
		this.useful = useful;
	}
	
	public String getImagePath()
	{
		return imagepath;
	}
	
	public void setImagePath(String imagepath)
	{
		this.imagepath = imagepath;
	}
	
	public String getFilePath()
	{
		return filepath;
	}
	
	public void setFilePath(String filepath)
	{
		this.filepath = filepath;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.TemplateType
	 * @return  the value of templateinformation.TemplateType
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public String getTemplatetype()
	{
		return templatetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.TemplateType
	 * @param templatetype  the value for templateinformation.TemplateType
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setTemplatetype(String templatetype)
	{
		this.templatetype = templatetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.HotDegree
	 * @return  the value of templateinformation.HotDegree
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public String getHotdegree()
	{
		return hotdegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.HotDegree
	 * @param hotdegree  the value for templateinformation.HotDegree
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setHotdegree(String hotdegree)
	{
		this.hotdegree = hotdegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.Color
	 * @return  the value of templateinformation.Color
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public String getColor()
	{
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.Color
	 * @param color  the value for templateinformation.Color
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setColor(String color)
	{
		this.color = color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.Name
	 * @return  the value of templateinformation.Name
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.Name
	 * @param name  the value for templateinformation.Name
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.CreatUser
	 * @return  the value of templateinformation.CreatUser
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public String getCreatuser()
	{
		return creatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.CreatUser
	 * @param creatuser  the value for templateinformation.CreatUser
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setCreatuser(String creatuser)
	{
		this.creatuser = creatuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column templateinformation.CreatTime
	 * @return  the value of templateinformation.CreatTime
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public Date getCreattime()
	{
		return creattime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column templateinformation.CreatTime
	 * @param creattime  the value for templateinformation.CreatTime
	 * @mbggenerated  Mon May 09 17:54:05 CST 2016
	 */
	public void setCreattime(Date creattime)
	{
		this.creattime = creattime;
	}
}